DROP TABLE IF EXISTS "fact_table";

CREATE TABLE "fact_table" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VendorID" int,
  "datetime_id" int UNIQUE,
  "passenger_count_id" int UNIQUE,
  "trip_distance_id" int UNIQUE,
  "pickup_location_id" int UNIQUE,
  "dropoff_location_id" int UNIQUE,
  "rate_code_id" int UNIQUE,
  "payment_type_id" int UNIQUE,
  "fare_amount" decimal,
  "extra" decimal,
  "mta_tax" decimal,
  "tip_amount" decimal,
  "tolls_amount" decimal,
  "improvement_surcharge" decimal,
  "total_amount" decimal
);

DROP TABLE IF EXISTS "datetime_dim";

CREATE TABLE "datetime_dim" (
  "datetime_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tpep_pickup_datetime" timestamp DEFAULT 'now()',
  "tpep_dropoff_datetime" timestamp DEFAULT 'now()'
);

DROP TABLE IF EXISTS "passenger_count_dim";

CREATE TABLE "passenger_count_dim" (
  "passenger_count_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passenger_count" int DEFAULT 0
);

DROP TABLE IF EXISTS "trip_distance_dim";

CREATE TABLE "trip_distance_dim" (
  "trip_distance_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trip_distance" decimal DEFAULT 0
);

DROP TABLE IF EXISTS "pickup_location_dim";

CREATE TABLE "pickup_location_dim" (
  "pickup_location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pickup_longitude" decimal,
  "pickup_latitude" decimal
);

DROP TABLE IF EXISTS "dropoff_location_dim";

CREATE TABLE "dropoff_location_dim" (
  "dropoff_location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dropoff_longitude" decimal,
  "dropoff_latitude" decimal
);

DROP TABLE IF EXISTS "rate_code_dim";

CREATE TABLE "rate_code_dim" (
  "rate_code_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RatecodeID" int,
  "rate_code_name" VARCHAR(50)
);

DROP TABLE IF EXISTS "payment_type_dim";

CREATE TABLE "payment_type_dim" (
  "payment_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_type" int,
  "payment_type_name" VARCHAR(50)
);

ALTER TABLE "passenger_count_dim" ADD FOREIGN KEY ("passenger_count_id") REFERENCES "fact_table" ("passenger_count_id");

ALTER TABLE "trip_distance_dim" ADD FOREIGN KEY ("trip_distance_id") REFERENCES "fact_table" ("trip_distance_id");

ALTER TABLE "pickup_location_dim" ADD FOREIGN KEY ("pickup_location_id") REFERENCES "fact_table" ("pickup_location_id");

ALTER TABLE "dropoff_location_dim" ADD FOREIGN KEY ("dropoff_location_id") REFERENCES "fact_table" ("dropoff_location_id");

ALTER TABLE "rate_code_dim" ADD FOREIGN KEY ("rate_code_id") REFERENCES "fact_table" ("rate_code_id");

ALTER TABLE "payment_type_dim" ADD FOREIGN KEY ("payment_type_id") REFERENCES "fact_table" ("payment_type_id");

ALTER TABLE "datetime_dim" ADD FOREIGN KEY ("datetime_id") REFERENCES "fact_table" ("datetime_id");
